#
# Copyright (C) 2013 Yoshinori Sato <ysato@users.sourceforge.jp>
#
# u-boot/board/renesas/ms7206se/Makefile
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= ms7206se.o
obj-y	+= lowlevel_init.o
