##
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# Copyright (C) 2014 Yoshinori Sato <ysato@users.sourceforge.jp>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= lowlevel_init.o edosk2674.o
